#ifndef APP_PROFILE_H
#define APP_PROFILE_H

// Supported sensor profiles.
#define APP_SENSOR_PROFILE_BME280 1
#define APP_SENSOR_PROFILE_BMP280 2
#define APP_SENSOR_PROFILE_SHT31  3

// Default profile for legacy SLCP files.
#ifndef APP_SENSOR_PROFILE
#define APP_SENSOR_PROFILE APP_SENSOR_PROFILE_BME280
#endif

#if (APP_SENSOR_PROFILE == APP_SENSOR_PROFILE_BMP280)
#define APP_PROFILE_HAS_HUMIDITY 0
#define APP_PROFILE_HAS_PRESSURE 1
#elif (APP_SENSOR_PROFILE == APP_SENSOR_PROFILE_SHT31)
#define APP_PROFILE_HAS_HUMIDITY 1
#define APP_PROFILE_HAS_PRESSURE 0
#else
#define APP_PROFILE_HAS_HUMIDITY 1
#define APP_PROFILE_HAS_PRESSURE 1
#endif

#endif // APP_PROFILE_H
